game:
  width: 50 # Width of the board
  height: 50 # Height of the board
  gif_length: 200 # Maximal number of iterations to record in output GIF file

# - [X, Y] (coordinates, 1-indexed) ([width, height] respectively) OR
# - [X1, Y1, X2, Y2] (to "draw" a uniform rectangle of cells)
# ([X_of_1st_corner, Y_of_1st_corner, X_of_2nd_corner, Y_of_2nd_corner])
cells:
  - [9, 10, 12, 10] # A line of 4 cells
  - [7, 12, 14, 12]
  - [5, 14, 16, 14]
  - [7, 16, 14, 16]
  - [9, 18, 12, 18]
